#!/bin/bash

UPTIME=$(cat /proc/uptime | cut -d ' ' -f 1)

echo "Content-Type: text/plain"
echo "Content-Length: ${#UPTIME}"
echo "Cache-Control: no-cache, no-store"
echo "Connection: close"
echo ""
echo -n "$UPTIME"
